import { privateDecrypt } from "crypto";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Member, SeidanMemberName, SEIDAN_ALL_MEMBERS } from "../types";
import { RankingTable } from "./components/RankingTable";

/*
  X: RankingTable
  A: おごりロジック
  B: モーダル
*/

const Home: NextPage = () => {
  // A: membersをstateで保持する
  const [members, setMembers] = useState([...SEIDAN_ALL_MEMBERS]);
  // X: ソートされたメンバーを定数で宣言する
  const rankedMembers = members.sort((a, b) => b.paidAmount - a.paidAmount);
  // B: モーダルを表示しているかどうかのstateを作成

  // A: 名前と金額を受け取り、その名前のmemberに金額分のpaidAmountを上乗せするメソッド
  const gochi = (payerName: SeidanMemberName, payment: number) => {
    // 方法１
    // payerNameとnameが同じか判定
    //　同じだった場合、paidAmoutにpaymentを上乗せ
    // 方法２
    // payerNameを持つmemberを指定
    // そのmemberのpaidAmountにpayment分を加える
    // 方法３
    // 支払い者とそれ以外を分離
    const payer: Member = members.filter(
      (member) => member.name === payerName
    )[0];
    const notPayers: Member[] = members.filter(
      (member) => member.name !== payerName
    );
    //　支払い者にpaymentを加算
    payer.paidAmount = payer.paidAmount + payment;
    // stateを更新
    notPayers.push(payer);
    setMembers(notPayers);
  };

  const openModal = () => {};

  // B: モーダルを閉じた状態にするメソッド
  const closeModal = () => {};

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>おごる担当はだれ？</h1>
        <input type="text" placeholder="おごる人" />
        <button>この人！</button>
        <div>
          {/* A: はじめに500円追加するボタンを実装 */}
          <button onClick={() => gochi("Hajime", 500)}>
            はじめ、ゴチになります！
          </button>
          {/* A: ひろむに500円追加するボタンを実装 */}
          <button onClick={() => gochi("Hiromu", 500)}>
            ひろむ、ゴチになります！
          </button>
          {/* A: こうすけに500円追加するボタンを実装 */}
          <button onClick={() => gochi("Kosuke", 500)}>
            こうすけ、ゴチになります！
          </button>
        </div>
        {/* B: モーダルを表示するボタン */}

        <input type="text" placeholder="追加メンバー" />

        {/* X: ソートされたメンバー情報を渡してRankingTableを表示する */}
        <RankingTable members={rankedMembers} />
        {/* B: モーダルを開いている状態ならばモーダルを表示 */}
      </main>
    </div>
  );
};

export default Home;
